### ISSUE TITLE
Initial dev setup

### ISSUE THREAD

**Issue by optikfluffel** [rizafahmi/elixirjobs#10]
Hi,

I just tried to get this thing up on my local machine but all I got was an error at [web/templates/page/dev.html.eex:4](https://github.com/rizafahmi/elixirjobs/blob/master/web/templates/page/dev.html.eex#L4):

```
[info] GET /
[info] Processing by ElixirJobs.PageController.index/2
  Parameters: %{"format" => "html"}
  Pipelines: [:browser]
[info] Sent 500 in 18ms
[error] #PID<0.312.0> running ElixirJobs.Endpoint terminated
Server: localhost:4000 (http)
Request: GET /
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol Access not implemented for {"b", []}
        (elixir) lib/access.ex:1: Access.impl_for!/1
        (elixir) lib/access.ex:33: Access.get/2
        (elixir_jobs) web/templates/page/dev.html.eex:4: ElixirJobs.PageView."dev.html"/1
        (elixir_jobs) web/templates/page/index.html.eex:70: anonymous fn/3 in ElixirJobs.PageView.index.html/1
        (stdlib) lists.erl:1261: :lists.foldl/3
        (elixir_jobs) web/templates/page/index.html.eex:69: ElixirJobs.PageView."index.html"/1
        (phoenix) lib/phoenix/view.ex:197: Phoenix.View.render_within/3
        (phoenix) lib/phoenix/view.ex:429: Phoenix.View.render_to_iodata/3
```

is there some more Fixture Data, that's not in the README, that's missing or did I do anything wrong?

**Comment by rizafahmi** [comment]
Hi @optikfluffel yeah, you probably right. I put the `devs` dummy data in th readme. Please try it out and report back to me. Thanks for your effort!

**Comment by optikfluffel** [comment]
Thanks :)
Now at least the page loads, but I'd guess that the dummy data for `jobs` is outdated? Looks like this for me now:

![screen shot 2015-08-04 at 11 43 24](https://cloud.githubusercontent.com/assets/379915/9057999/26e271d4-3a9e-11e5-8fe1-42db39915d01.png)

and in `job.html.eex` you use (among others) `@job["title"]` and `@job["company"]` which both aren't in your fixtures.

**Comment by rizafahmi** [comment]
oh yeah. I'll updated it.

**Comment by rizafahmi** [comment]
@optikfluffel what about now?

**Comment by optikfluffel** [comment]
Seems to work fine now, thanks :heart_decoration: 
Just a little thing, maybe the README should say that you have to create the `test` database and the `jobs`, `devs` and `users` tables in it, otherwise it'll crash.

**Comment by rizafahmi** [comment]
Yeah. I'll do. Thanks for your help!
