### ISSUE TITLE
Feature: Allow people to report dead jobs

### ISSUE THREAD

**Issue by ctro** [rizafahmi/elixirjobs#25]
Full disclosure this job posting was created by an old employee:
http://jobs.elixirdose.com/job/52382762-e046-4377-ab36-eeaf9ca2ea20

I don't have any way of deleting it or reporting it as stale. We're still getting emails from interested people and I hate breaking all of those hearts.

**Comment by rizafahmi** [comment]
Sorry for that. I'll delete it. Thank you for reporting this.

**Comment by rizafahmi** [comment]
@ctro did you found Elixir devs? Just curious :)

**Comment by ctro** [comment]
Thanks Riza!

You know, we had an elixir dev on board at the time, but this company is,
ahem, not growing anymore :)  We turned down our Elixir hiring knob shortly
after posting job listings.

But we DID see (and continue to see ;) lots of great candidates who I would
have been very excited to interview.

**Comment by rizafahmi** [comment]
Thanks @ctro for your info. Hopefully this job site will help companies like yours. Goodluck with everything!
