### ISSUE TITLE
Pop up makes site unusable on iPhone 6+

### ISSUE THREAD

**Issue by joefiorini** [rizafahmi/elixirjobs#47]
In the attached screenshot I could not access the create account button or the confirm password input. The pop up also blocks links in the footer and makes it really hard to read the posts. Is there an easy way to dismiss the pop up? Or make it not so obtrusive?

![img_2598](https://user-images.githubusercontent.com/3648/27937582-385b491a-6286-11e7-9e62-db8dffb69d8e.PNG)

**Comment by rizafahmi** [comment]
I take it off. Sorry about that @joefiorini
