### ISSUE TITLE
Typo on flash when creating an account

### ISSUE THREAD

**Issue by pdgonzalez872** [rizafahmi/elixirjobs#51]
Hi! Thanks for the website! Pretty cool project. I signed up and saw a typo when creating an account.

Here is the diff that I think could fix this if you are interested:

```
diff --git a/web/controllers/user_controller.ex b/web/controllers/user_controller.ex
index 39b4d23..86bef26 100644
--- a/web/controllers/user_controller.ex
+++ b/web/controllers/user_controller.ex
@@ -30,7 +30,7 @@ defmodule ElixirJobs.UserController do
     if result.data["errors"] == 0 do
       conn
       |> put_session(:user, params["email"])
-      |> put_flash(:info, "Super! Your account created.")
+      |> put_flash(:info, "Super! Your account was created.")
       |> redirect(to: params["redir"] || "/")
       |> halt
     else
```

I created #52 for you.

**Comment by pdgonzalez872** [comment]
As I created a profile, I found another one, so I'll add a commit for that one as well.
![image](https://user-images.githubusercontent.com/8906358/35785802-e3a9e0ce-09e8-11e8-84fe-df92fdf5a0e2.png)

I looked at the controller and saw another one for `updated`. 0b24c1e3d5a9469238e6727f868aa5731cf26444 fixes both of them.

Hope this helps.

**Comment by manusajith** [comment]
@pdgonzalez872 Thanks for the PR.!

Could you please change the target of the PR to [this](https://github.com/manusajith/elixirjobs) fork pls. The project is now being maintained there. Tnx in advance.

**Comment by pdgonzalez872** [comment]
alright, created https://github.com/manusajith/elixirjobs/issues/8 and we can leave this issue as is then.
