### ISSUE TITLE
change description to correct website 

### ISSUE THREAD

**Issue by MichaelDimmitt** [rizafahmi/elixirjobs#53]
The current description sends you to 
"the site cannot be reached"

current description:
Job portal for Alchemist http://jobs.elixirdose.com

correct url:
https://elixir.career/

**Comment by manusajith** [comment]
@MichaelDimmitt Thanks for reporting the issue. Please note that the repo for the website is now maintained [here](https://github.com/manusajith/elixirjobs)

**Comment by MichaelDimmitt** [comment]
Thanks for the update
