### ISSUE TITLE
Add RSS Feeds

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/elixirjobs#7]

**Comment by optikfluffel** [comment]
I'd like to give this a try using [BennyHallett/elixir-rss](https://github.com/BennyHallett/elixir-rss) after #11 and #12 are merged.

**Comment by rizafahmi** [comment]
Nice!

**Comment by optikfluffel** [comment]
Do we need any other feeds than a jobs feed for now?

**Comment by rizafahmi** [comment]
Devs maybe?

**Comment by optikfluffel** [comment]
So should I change the urls to `/feed/jobs` and `/feed/devs` then or let the jobs feed as it is in the PR and just add `/feed/devs`? Or maybe you have a completely different idea?

**Comment by rizafahmi** [comment]
Option no. 2 is ok for me. So just add `/feed/devs`.

**Comment by optikfluffel** [comment]
I just saw that user profiles don't have a `date_created` or something similar. Should I change it _here_ and add it when a new profile is created? Or should I have a closer look at `elixir-rss` to see wether it's complicated to make `pubDate` optional for feed items there?

**Comment by rizafahmi** [comment]
I think better we have `date_created` thing. What do you think?

**Comment by optikfluffel** [comment]
Having a `date_created` should be better, yes. We'd probably need it later on for stuff like sorting and paging anyway. Do you want to migrate old user data and add a date to every single one there or should there be a default date (`1970-01-01` ?) in the code that's used when there is none in the database yet?

Oh and one more thing: what about something like `date_updated`, do we need it?

**Comment by rizafahmi** [comment]
Hmm.. What if the date is null, just don't show it?

For `date_updated`, it could be useful one day.

**Comment by optikfluffel** [comment]
We need some sort of date as a `<pubDate>` for now, until [BennyHallett/elixir-rss#6](https://github.com/BennyHallett/elixir-rss/issues/6) is closed.
