### ISSUE TITLE
Registering fails

### ISSUE THREAD

**Issue by larshesel** [rizafahmi/elixirjobs#8]
When trying to register at jobs.elixirdose.com I'm always told the passwords are not the same (Password should be the same) and cannot continue - although I pasted the password into both fields.

**Comment by rizafahmi** [comment]
Hi @larshesel. Thanks for reporting this. Could you care to try again? The javascript library was buggy :'(

**Comment by larshesel** [comment]
Hey @rizafahmi - yep, it works now. Thanks for the quick turnaround time! :+1:

**Comment by rizafahmi** [comment]
I'm glad it's working now. Thanks a bunch @larshesel !
